local tl = require("tl")

describe("typecheck", function()
   it("type errors include filename", function ()
      local tokens = tl.lex("local x: string = 1")
      local _, ast = tl.parse_program(tokens, {})
      local errors, unknowns = tl.type_check(ast, false, "foo.tl")
      assert.same("foo.tl", errors[1].filename, "type errors should contain .filename property")
   end)

   it("unknowns include filename", function ()
      local tokens = tl.lex("local x: string = b")
      local _, ast = tl.parse_program(tokens, {})
      local errors, unknowns = tl.type_check(ast, true, "foo.tl")
      assert.same("foo.tl", unknowns[1].filename, "unknowns should contain .filename property")
   end)
end)
